config/routes.rb
Rails.application.routes.draw do
  
  authenticate :user, ->(user) { user.superadmin_role? } do
    mount Blazer::Engine, at: "blazer"
  end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'user/index'
  get 'user/show'
  get 'user/new'
  get 'user/edit'
  get 'user/create'
  get 'user/destroy'
  get 'user/update'
  devise_for :users
  
  get '/commercial', to: 'pages#commercial'
  get '/residential', to: 'pages#residential'
  get '/form', to: 'pages#form'  
  get '/thank-you', to: 'pages#thankyou'
  post '/form', to: 'form#create'
  post '/contact-us', to: 'contact_us_form#create'
  # get '/chart', to: 'application#postgres_update'

  get '/chart-page', to: 'pages#chart'
  get '/chart', to: 'application#view_chart'
  get '/warehouse-update', to: 'application#postgres_update'

  root 'pages#home'


  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
      user ||= User.new # guest user (not logged in)
      #can :manage, :all  # <---------- TO GIVE TEMPORARY ACCESS TO EVERYTHING FOR EVERYONE
      if user.superadmin_role?
            can :manage, :all
            can :access, :rails_admin       # only allow admin users to access Rails Admin
            can :manage, :dashboard         # allow access to dashboard
      elsif user.employee_role?
            can :manage, Quote
            can :access, :rails_admin       # only allow admin users to access Rails Admin
            can :manage, :dashboard         # allow access to dashboard
      else
            #can :read, :all
            authorize! :access, :rails_admin
            authorize! :read, Quote
            authorize! :destroy, Quote  
      end

    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/adress.rb
class Adress < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    has_many :column
    
end

app/models/building.rb
class Building < ApplicationRecord
    belongs_to :customer
    has_many :battery
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
    belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery
    has_many :elevator
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :building
end

app/models/elevator.rb
class Elevator < ApplicationRecord
    belongs_to :column
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_one :user
end

app/models/lead.rb
class Lead < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commercial_helper.rb
module CommercialHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>Rocket Elevators</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <%= favicon_link_tag asset_path('favicon-16x16.png') %>
    
    <%= javascript_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<!--
    <%= javascript_include_tag 'application', 'all': 'reload' %>
    <%= stylesheet_link_tag    'extralayers', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'form', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'settings', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'essentials', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'layout', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'red', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://use.fontawesome.com/releases/v5.0.10/css/all.css' %>  
    <%= stylesheet_link_tag    'https://cdn.jsdelivr.net/npm/et-line@1.0.1/style.min.css' %>
-->


    <%= render 'partials/header' %>
    
    <% unless flash.empty? %>
          <script type="text/javascript">
            <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
          </script>
        <% end %>

  </head>

  <body class="enable-animation">
    <%= yield %>
    
    <%= render 'partials/footer' %>
    <%= javascript_include_tag 'jquery.themepunch.tools.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.themepunch.revolution.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'demo.revolution_slider.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.mixitup.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'scripts', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'contact', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'smoothscroll', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.nav.min', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/chart.erb
<!-- wrapper -->
<div class="container">
	<!-- CALLOUT -->
	<div class="callout alert alert-transparent b-0 rad-0 m-0 pt-60 pb-60 clearfix">
		<div class="text-center">
			<h3>Update the data warehouse and go to the charts page</h3>
			<a href="/warehouse-update" class="btn btn-primary btn-lg btn-round mt-30" >UPDATE DATA WAREHOUSE !</a>
			<p class="font-lato fs-20">It can take a few minutes...</p>
		</div>
	</div>
	<!-- /CALLOUT -->

	<!-- divider -->
	<div class="divider divider-center divider-color">
		<i class="fa fa-chevron-down"></i>
	</div>
	<!-- /divider -->
			
	<!-- CALLOUT -->
	<div class="callout alert alert-transparent b-0 rad-0 m-0 pt-60 pb-60 clearfix">
		<div class="text-center">
			<h3>Go to the charts page</h3>
			<a href="/chart" class="btn btn-primary btn-lg btn-round mt-30" >GO TO CHARTS !</a>
			<p class="font-lato fs-20">Just go to the charts page without upload the database</p>
		</div>
	</div>
	<!-- /CALLOUT -->			
</div>
<!-- /wrapper -->

<!-- SCROLL TO TOP -->
<a href="#" id="toTop"></a>
<!-- SCROLL TO BOTTOM -->
<a name="bottom"></a>

app/views/pages/commercial.html.erb
			<section class="b-0">
				<div class="container">
					<header class="text-center">
						<h2 class="m-0">Commercial Services</h2>
						<p class="font-lato fs-20 m-0">We truly care about our customers</p>
					</header>
					<p class="lead">
						Rocket Elevators know you need your elevators, escalators and other
						people transportation systems operating optimally at all times.
						That’s why, across our top priority is provide high standing
						Commercial elevators, efficiency and safety. Industry-leading
						knowledge, processes and tools enable us to deliver on this
						priority. So do our topnotch technicians with their continuous
						training and comprehensive manufacturer-independent expertise. This
						is your guarantee of service excellence.
					</p>

					<div class="divider divider-center divider-color">
						<!-- divider -->
						<i class="fa fa-chevron-down"></i>
					</div>

					<!-- FEATURED BOXES 3 -->

					<!-- /FEATURED BOXES 3 -->
				</div>

				<div class="container">
					<div class="row">
						<div class="col-md-4">
							<div class="box-icon box-icon-left box-icon-round">
								<a class="box-icon-title" href="form">
									<i class="fas fa-shopping-cart"></i>
									<h2>A ONE-STOP SHOP</h2>
								</a>
								<p>
									With us you get everything you need to ensure smooth people
									flow from the front door to the final destination.
								</p>
							</div>
						</div>
						<div class="col-md-4">
							<div class="box-icon box-icon-left box-icon-round">
								<a class="box-icon-title" href="/#services">
									<i class="fas fa-globe-americas"></i>
									<h2>WORLD-CLASS SERVICES</h2>
								</a>
								<p>
									We offer services and support for every step of your project -
									from building design to construction.
								</p>
							</div>
						</div>
						<div class="col-md-4">
							<div class="box-icon box-icon-left box-icon-round">
								<a class="box-icon-title" href="/#work">
									<i class="fas fa-calendar-alt"></i>
									<h2>44 YEARS OF EXPERIENCE</h2>
								</a>
								<p>
									For more than 44 years, we’ve been excelling at projects:
									from affordable housing to the world’s tallest buildings.
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>

			<!-- / -->



			<!-- VISUAL CHART -->
			<section class=" pt-0" style="background-color:#fbfbfb">
				
				<!-- top curved -->
				<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" viewBox="0 0 100 100" preserveAspectRatio="none" style="fill:#ffffff;padding:0;margin:0;display:block;position:relative;z-index:100;"><path d="M0 0 C55 180 100 0 100 0 Z"></path></svg>

				<!--
					Available Classes/Colors
						.cart-visual-warning
						.cart-visual-info
						.cart-visual-success
						.cart-visual-danger
						.cart-visual-default
				-->
				<div class="clearfix mt-60 cart-visual cart-visual-warning">

					<svg id="cart-visual-svg-1" height="0" width="100%" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1096 131.25" style="height: 140px;" xml:space="preserve">
						<path d="M782,49.418c-58.667-24.667-118.602-46-249.334-46s-159.43,36.157-209.333,62.207C259.04,99.186,0,131.25,0,131.25h1096C1096,131.25,840.667,74.085,782,49.418z"></path>
					</svg>

					<svg id="cart-visual-svg-2" height="0" width="100%" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1133.338 144.499" style="height: 195px;" xml:space="preserve">
						<path d="M948.868,144.499H0V72.249c26.67-9.407,66.707-19.582,119.535-19.582c133.999,0,227.999,39.333,332.665,39.333c80,0,142.667-36.666,174.667-52.666S716.201,0,804.201,0s144.667,20,144.667,20c44.173,10.997,122.713,47.543,184.47,78.215v46.284H948.868z"></path>
					</svg>

					<div class="container">

						<div class="row">

							<div class="col-6 col-md-3 mt--30 pb-180">
								<div class="cart-visual-pin"><div class="cart-visual-pin-ball">&nbsp;</div></div>
								<div class="pl-20 pr-20">
									<h2><i class="countTo" data-speed="1600">6000</i>+</h2>
									<p class="fw--300">Happy Returning Customers</p>
									
								</div>
							</div>

							<div class="col-6 col-md-3 mt-80">
								<div class="cart-visual-pin"><div class="cart-visual-pin-ball">&nbsp;</div></div>
								<div class="pl-20 pr-20">
									<h2><i class="countTo" data-speed="1300">100</i>%</h2>
									<p class="fw--300">Money back gurantee</p>
									
								</div>
							</div>

							<div class="col-6 col-md-3 mt-60">
								<div class="cart-visual-pin"><div class="cart-visual-pin-ball">&nbsp;</div></div>
								<div class="pl-20 pr-20">
									<h2><i class="countTo" data-speed="900">235</i>%</h2>
									<p class="fw--300">Average customer growth</p>
									
								</div>
							</div>

							<div class="col-6 col-md-3 mt-0">
								<div class="cart-visual-pin"><div class="cart-visual-pin-ball">&nbsp;</div></div>
								<div class="pl-20 pr-20">
									<h2><i class="countTo" data-speed="2000">250000</i></h2>
									<p class="fw--300">Work hours saved last 12 months</p>
									
								</div>
							</div>

						</div>

					</div>

				</div>
			</section>
			<!-- /VISUAL CHART -->



			<!-- -->
			<section>
				<div class="container">
					<header class="text-center">
						<h2 class="m-0">Features</h2>
						<p class="font-lato fs-20 m-0">
							We provide the highest quality of elevator
						</p>
					</header>

					<hr />

					<div class="row mt-80">
						<div
							class="col-lg-4 col-md-4 push-md-4 text-center order-md-2 order-lg-2"
						>
							<img class="img-fluid" src="<%= asset_path( 'Elevator.jpg' ) %>" alt="" />
						</div>

						<div class="col-lg-4 col-md-4 col-sm-6 order-md-1 order-lg-1">
							<div class="box-icon box-icon-right">
								<a class="box-icon-title" >
									<i class="fa fa-eye"></i>
									<h2>Enhancing Energy Efficiency</h2>
								</a>
								<p>
									The joint-lapped core built in the PM motor of the traction
									machine features flexible joints. T
								</p>
							</div>

							<div class="box-icon box-icon-right">
								<a class="box-icon-title" >
									<i class="fa fa-check"></i>
									<h2>Devices that Use Less Energy</h2>
								</a>
								<p>
									Energy-efficient LEDs consume less power than conventional
									lamps. Used for ceiling lights and hall lanterns, LEDs boost
									the overall energy performance of the building.
								</p>
							</div>

							<div class="box-icon box-icon-right">
								<a class="box-icon-title" >
									<i class="fa fa-rocket"></i>
									<h2>Smooth Mobility</h2>
								</a>
								<p>
									When a building is expected to have heavy traffic, optimum car
									allocation suited for every condition makes a big difference
									in preventing congestion at a lobby floor and reducing long
									waits.
								</p>
							</div>
						</div>

						<div class="col-lg-4 col-md-4 col-sm-6 order-md-3 order-lg-3">
							<div class="box-icon box-icon-left">
								<a class="box-icon-title" >
									<i class="fa fa-tablet"></i>
									<h2>Maximizing Operational Efficiency</h2>
								</a>
								<p>
									This system selects the elevator in a group that best balances
									operational efficiency and energy consumption. Priority is
									given to operational efficiency during peak hours and energy
									efficiency during non-peak hours
								</p>
							</div>

							<div class="box-icon box-icon-left">
								<a class="box-icon-title" >
									<i class="fa fa-random"></i>
									<h2>Clean Design</h2>
								</a>
								<p>
									Great care is taken in the design and manufacture of each and
									every elevator part to ensure a comfortable, user-friendly
									ride.
								</p>
							</div>

							<div class="box-icon box-icon-left">
								<a class="box-icon-title" >
									<i class="fa fa-tint"></i>
									<h2>Fire Emergency Return</h2>
								</a>
								<p>
									Upon activation of a key switch or a building‘s fire alarm,
									all calls are canceled, all cars immediately return to a
									specified evacuation floor and the doors open to facilitate
									the safe evacuation of passengers
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- / -->
			<section>
				<div class="container">
					<header class="text-center">
						<h2 class="m-0">Commercial Elevators</h2>
						<p class="font-lato fs-20 m-0">Best prices in the market</p>
					</header>

					<hr />

					<div class="container">
						<div class="row">
							<div class="col-md-4 col-sm-4">
								<div class="price-clean">
									<h4><sup>$</sup>7565<em></em></h4>
									<h5>STARTER</h5>
									<hr />
									<p class="text-uppercase">Standard model</p>
									<hr />
									<a href="form" class="btn btn-3d btn-teal text-uppercase">Estimate My Project !</a>
								</div>
							</div>

							<div class="col-md-4 col-sm-4">
								<div class="price-clean price-clean-popular">
									<div class="ribbon">
										<div class="ribbon-inner">POPULAR</div>
									</div>
									<h4><sup>$</sup>12,345<em></em></h4>
									<h5>STARTER</h5>
									<hr />
									<p class="text-uppercase">Premium Model</p>
									<hr />
									<a href="form" class="btn btn-3d btn-primary text-uppercase">Estimate My Project !</a>
								</div>
							</div>

							<div class="col-md-4 col-sm-4">
								<div class="price-clean">
									<h4><sup>$</sup>15,400<em></em></h4>
									<h5>STARTER</h5>
									<hr />
									<p class="text-uppercase">Excelium model</p>
									<hr />
									<a href="form" class="btn btn-3d btn-teal text-uppercase">Estimate My Project!</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section>
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<h3 class="fs-20">Why chose us?</h3>
							<ul class="list-unstyled">
								<li>
									<i class="fa fa-check"></i> Rocket Elevators's success lies in
									its commitment to running events with professionalism and
									expertise, and in identifying strongly with their outcome.
								</li>

								<li>
									<i class="fa fa-check"></i> The sense of responsibility means
									we always strive to add value and are pro-active in solving
									problems and in adopting client procedures.
								</li>
								<li>
									<i class="fa fa-check"></i> Our approach is distinctly
									innovative. We constantly seek new ways to increase client
									visibility and brand value. We also look to get the most out
									of advances in digitalisation, and embrace client technology
									platforms.
								</li>
								<li>
									<i class="fa fa-check"></i> Our approach is distinctly
									innovative. We constantly seek new ways to increase client
									visibility and brand value.
								</li>
								<li>
									<i class="fa fa-check"></i> We offer free support because we
									care about your company.
								</li>
							</ul>
						</div>

						<div class="col-md-6">
							<h3 class="fs-20 text-center">
								Rocket Elevators commercial solutions clients
							</h3>
							<!-- 
								Note: remove class="rounded" from the img for squared image!
							-->
							<ul class="row clearfix testimonial-dotted list-unstyled">
								<li class="col-md-6">
									<div class="testimonial">
										<figure class="float-left">
											<img
												class="rounded"
												src="<%= asset_path( 'logo02.png' ) %>"
												alt=""
											/>
										</figure>
										<div class="testimonial-content">
											<p>
												Rocket Elevators has the expertise to modernize
												hydraulic and traction elevators from all manufacturers.
											</p>
											<cite>
												Saad Eddine
												<span
													>Arrogant<br />
													Chiken INC.</span
												>
											</cite>
										</div>
									</div>
								</li>
								<li class="col-md-6">
									<div class="testimonial">
										<figure class="float-left">
											<img
												class="rounded"
												src="<%= asset_path( 'logo04.jpg' ) %>"
												alt=""
											/>
										</figure>
										<div class="testimonial-content">
											<p>
												Elevator group control systems can make decisions using
												fragmentary and fuzzy logic concepts.
											</p>
											<cite>
												Steve Armin
												<span>Bon mignon</span>
											</cite>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</section>
			<!-- / -->

			<!-- CALLOUT -->

			<div
				class="callout alert alert-transparent b-0 rad-0 m-0 pt-60 pb-60 clearfix"
			>
				<div class="text-center">
					<h3>
						Call now at <span><strong> (581) 701-0303</strong></span> and get 15%
						discount!
					</h3>
					<p class="font-lato fs-20">
						We truly care about our users and our product.
					</p>

					<a
						href="/#contact"
						class="btn btn-primary btn-lg btn-round mt-30"
						>CONTACT US NOW</a
					>
				</div>
			</div>
			<!-- /CALLOUT -->
				
		</div>
		<!-- /wrapper -->

		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>
	</body>
	<!-- SCROLL TO BOTTOM -->
	<a name="bottom"></a>

app/views/pages/thankyou.html.erb
<!-- wrapper -->
<div class="container">
	<header class="text-center pt-60 pb-60 ">
		<h2 class="m-0">Thank you for your contact</h2>
		<p class="font-lato fs-20 m-0">Our team will contact you soon !</p>
	</header>

	<!-- divider -->
	<div class="divider divider-center divider-color">
		<i class="fa fa-chevron-down"></i>
	</div>
	<!-- /divider -->
			
	<!-- CALLOUT -->
	<div class="callout alert alert-transparent b-0 rad-0 m-0 pt-60 pb-60 clearfix">
		<div class="text-center">
			<h3>Call now at <span><strong> (581) 701-0303</strong></span> and get 15% discount!</h3>
			<p class="font-lato fs-20">We truly care about our users and our product.</p>
			<a href="/form" class="btn btn-primary btn-lg btn-round mt-30" >GET A QUOTE</a>
		</div>
	</div>
	<!-- /CALLOUT -->			
</div>
<!-- /wrapper -->

<!-- SCROLL TO TOP -->
<a href="#" id="toTop"></a>
<!-- SCROLL TO BOTTOM -->
<a name="bottom"></a>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Rocket Elevators</title>
		<meta name="description" content=" Rocket Elevators make professional elevators quebec canada" />
		<meta name="Author" content="Saad Eddine FEKI [CodeBoxx]" />

		<!-- mobile settings -->
		<meta
			name="viewport"
			content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0"
		/>
		
		<!-- RAILS CSS/JS -->
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
		<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
		<%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'%>

		<!-- WEB FONTS : use %7C instead of | (pipe) -->
		<link
			href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"
			rel="stylesheet"
			type="text/css"
		/>
		<!-- Rocket elevators Favicon -->
		<%# <link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
			integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
			crossorigin="anonymous"
		/> %>
		<link
			rel="icon"
			type="image/png"
			href="<%= asset_path( 'favicon-16x16.png' ) %>"
		/>
		<!-- CORE CSS -->

	</head>

	<body class="smoothscroll enable-animation">
		

		<!-- wrapper -->
		<div id="wrapper">
			
<div id="header" class="navbar-toggleable-md sticky clearfix">
    <!-- TOP NAV -->
    <header id="topNav">
      <div class="container">
        <!-- Mobile Menu Button -->
        <button class="btn btn-mobile"
          data-toggle="collapse"
          data-target=".nav-main-collapse">
          <i class="fa fa-bars"></i>
        </button>

        <!-- Logo -->
        <a class="logo float-left scrollTo" href="#top">
          <img src="<%= asset_path( 'logo-inc.png' ) %>">							
        </a>

        <!--
          Top Nav
        -->
    <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark" >
          <nav class="nav-main">
            <!--
              .nav-onepage
              Required for onepage navigation links

              Add .external for an external link!
            -->
            
							<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active">
										<!-- HOME -->
										<a href="/"> HOME </a>
									</li>
									<li class="dropdown"><!-- SERVICES -->
										<a class="dropdown-toggle" href="#">
											SERVICES
										</a>
										<ul class="dropdown-menu">
											<li class="dropdown">
												<%= link_to 'COMMERCIAL', commercial_path %>
											</li>
											<li class="dropdown">
												<%= link_to 'RESIDENTIAL', residential_path %>
											</li>
											<li class="dropdown">
												<%= link_to 'REQUEST FOR QUOTE', form_path %>
											</li>
										</ul>
									</li>

									<li>
										<!-- WORK -->
										<%= link_to "PORTFOLIO", "#{root_path}#work" %>
									</li>
									<li>
										<!-- NEWS -->
										<%= link_to "NEWS", "#{root_path}#news" %>
									</li>

									<li>
										<!-- CLIENTS -->
										<%= link_to "CLIENTS", "#{root_path}#clients" %>
									</li>

									<li>
										<!-- CONTACT -->
										<%= link_to "CONTACT", "#{root_path}#contact" %>
									</li>

									<li class="dropdown"><!-- SERVICES -->
										<a class="dropdown-toggle" href="#">
											MEMBER
										</a>
										<ul class="dropdown-menu">
											<% if !current_user %>
											<li><%= link_to "LOGIN", new_user_session_path %></li>
											<li><%= link_to "SIGN UP", new_user_registration_path %></li>
										<% elsif current_user.superadmin_role? %>
											<li><%= link_to "ADMIN PANEL", rails_admin_path %> </li>
											<li><%= link_to "CHART VIEWER", chart_path %> </li>
											<li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
										<% elsif current_user.employee_role? %>
											<li><%= link_to "ADMIN PANEL", rails_admin_path %> </li>
											<li><%= link_to "EDIT USER", edit_user_registration_path %></li>
											<li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
										<% else %>
											<li><%= link_to "PROFILE", edit_user_registration_path %></li>
											<li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
										<% end %>
										</ul>
									</li>
								</ul>
							</nav>
						</div>
					</div> 	
				</header>
				<!-- /Top Nav -->
			</div>
    </div>